# Generated by Django 6.0.1 on 2026-02-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글 목록",
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/%y/%m/%d", verbose_name="이미지"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("free", "자유"),
                    ("travel", "여행"),
                    ("cat", "고양이"),
                    ("dog", "강아지"),
                ],
                default="free",
                max_length=10,
                verbose_name="카테고리",
            ),
        ),
    ]
