# Generated by Django 6.0.1 on 2026-02-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_options_blog_image_alter_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/%y/%m/%d/thumbnail",
                verbose_name="썸네일",
            ),
        ),
    ]
